// vue-app/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <Greeting />
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <elastic-star-rating :max-rating="5" style="display: block; position: absolute; top: 100px;"></elastic-star-rating>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
    <p>
      This is my amazing Vue app. Not convinced? You have to rate it to see it!
    </p>
  </div>
</template>

<script>
import Greeting from './components/Greeting.vue'

export default {
  name: 'App',
  components: {
    Greeting
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react-app/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { Greeting } from './Greeting';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <Greeting/>
        <p>
          This is my amazing React app. Not convinced? You have to rate it to see it!
        </p>
        <elastic-star-rating max-rating={10} style={{display: "block", position: "absolute", top: "0"}}></elastic-star-rating>
      </header>
    </div>
  );
}

export default App;
